### PR TITLE
Updating tbSystem to include the '-echo' flag in the system call

### PR DESCRIPTION
**Pull request by spitschan**
This will allow for interactive use of system commands.

### CODE REVIEW

**Comment by benjamin-heasly** [comment]
Checked this out and ran the automated tests.  Works great.

**Comment by benjamin-heasly** [comment]
My only suggestion/question is should we make the echo optional and add this option as a parameter for tbSystem()?  My thinking is for some commands like ping, we might not care to see all the output.

**Comment by spitschan** [comment]
@benjamin-heasly I'm not sure how to make this optional? Could you perhaps implement this and then merge? Thanks.

**Comment by benjamin-heasly** [comment]
Yerp.  Just a sec.

**Comment by benjamin-heasly** [comment]
Made the "echo" optional and merged manually.

If you're curious, I made it optional with the inputParser:
  https://github.com/ToolboxHub/ToolboxToolbox/blob/master/api/tbSystem.m#L15

**Pull request merged**
